version: "3"

services:
  database:
    image: postgres:9.5-alpine
    container_name: loja-virtual-spring-postgres-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dbloja
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
