services:
  database:
    image: postgres
    container_name: loja-virtual-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=lojadb
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
